### ISSUE TITLE
Feature request: vendor-prefixed properties alignment

### ISSUE THREAD

**Issue by niksy** [emmetio/emmet#142]
Right now, when you expand some property to its vendor-prefixed variant, you get this output:

``` css
div {
    -webkit-transform: ;
    -moz-transform: ;
    -ms-transform: ;
    -o-transform: ;
    transform: ;
}
```

It would be nice if the engine could align those properties to this output:

``` css
div {
    -webkit-transform: ;
       -moz-transform: ;
        -ms-transform: ;
         -o-transform: ;
            transform: ;
}
```

That way, you could see easily what values you have for every property, what needs to be changes for specific rendering engine, etc.
