### ISSUE TITLE
Word-wrap и -ms

### ISSUE THREAD

**Issue by pustovalov** [emmetio/emmet#207]
ww-nm и все свойтства с word-wrap emmet раскрывает так:

``` css
.block {
    -ms-word-wrap: normal;
    word-wrap: normal;
}
```

Префикса -ms для word-wrap вроде бы не существует.
