### ISSUE TITLE
Invalid reflection of CSS gradient

### ISSUE THREAD

**Issue by sergeche** [emmetio/emmet#239]
In code snippet like this:

``` css
body {
    background: -moz-linear-gradient(top, #ffed8c, #f7c4ff);
    background: -ms-linear-gradient(top, #ffed8c, #f7c4ff);
    background: -o-linear-gradient(top, #ffed8c, #f7c4ff);
    background: -webkit-gradient(linear, center top, center bottom, from(#ffed8c), to(#f7c4ff));
    background: -webkit-linear-gradient(top, #ffed8c, #f7c4ff);
    background: linear-gradient(top, #ffed8c, #f7c4ff);
}
```

if caret is inside old WebKit gradient definition, all `background` properties receive this definition.
