### ISSUE TITLE
Update Image Size not works on .SCSS file

### ISSUE THREAD

**Issue by joel611** [emmetio/emmet#246]
Hi,

consider the situation like this.

this works

``` SCSS
.class-a{background:url('temp.jpg');}  
```

but this one not works

``` SCSS
.class-a{background:url('temp.jpg'); 
    .class-b{}
}
```

i believe this is because it didn't know where to append the width,height property.
