### ISSUE TITLE
Increase CSS comments switch

### ISSUE THREAD

**Issue by yisibl** [emmetio/emmet#272]
Comments can help us better understand the CSS code snippet, a better understanding of browser compatibility.
Therefore, the proposed increase in the output of a switch can comment, such as "| c" (if the conflict, hope to have a better way).
## snippets.json defines the following code fragment:

``` json
"@f+": "@font-face {\n\tfont-family: '${1:FontName}'; /* Custom font name */\n\tsrc: url('${2:FileName}.eot'); /* IE9+ */\n\tsrc: url('${2:FileName}.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */\n\t\t url('${2:FileName}.woff') format('woff'), /* Chrome,Firefox */\n\t\t url('${2:FileName}.ttf') format('truetype'), /* Chrome,Firefox,Opera,Safari,Android, iOS 4.2+ */\n\t\t url('${2:FileName}.svg#${1:FontName}') format('svg'); /* iOS 4.1- */${3}\n}"
```
## Enter "@ f + | c"

 output:

``` css
@font-face {
    font-family: 'FontName'; /* Custom font name */
    src: url('FileName.eot'); /* IE9+ */
    src: url('FileName.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */
         url('FileName.woff') format('woff'), /* Chrome,Firefox */
         url('FileName.ttf') format('truetype'), /* Chrome,Firefox,Opera,Safari,Android, iOS 4.2+ */
         url('FileName.svg#FontName') format('svg'); /* iOS 4.1- */
}
```
## Enter "@ f +"

output:

``` css
@font-face {
    font-family: 'FontName';
    src: url('FileName.eot');
    src: url('FileName.eot?#iefix') format('embedded-opentype'),
         url('FileName.woff') format('woff'),
         url('FileName.ttf') format('truetype'),
         url('FileName.svg#FontName') format('svg');
}
```
