### ISSUE TITLE
CSS: incorrect “toggle comment” action behavior

### ISSUE THREAD

**Issue by sergeche** [emmetio/emmet#63]
See this example

``` css
.class {
    position: relative;
    /* background: url(../i/panel-bg.jpg) #412a18; */
    width: 100%;|
    height: 100%;
    overflow: hidden;
}
```
