### ISSUE TITLE
Invalid generate definition

### ISSUE THREAD

**Issue by sergeche** [emmetio/emmet#90]
Fails to generate correct gradient definitions from this code

``` css
.main-content {
  border-radius: 0 0 0.3em 0.3em;

  background-image: lg(red, green) <-- I expand here

  -webkit-box-shadow: inset 0 0.1em 0.2em 0 #000;
}
```
